### PR TITLE
[C++] Faster.h - Optimization power of 2

### PR DESCRIPTION
**Pull request by aabbdev**
We should do a benchmark, it should be faster now.

EDIT: I made these modifications from my browser I will compile locally to see

### CODE REVIEW

**Comment by aabbdev** [comment]
I have applied this optimization almost everywhere in the code, I have gained 200 ms on a memory test, I just have to put the segments in power of 2

**Comment by badrishc** [comment]
Note that if a value is already a power of 2, C++ compiler automatically performs the optimization to avoid %. So code readability can be maintained.

**Comment by aabbdev** [comment]
I didn't finish the commit, but yes indeed the code is automatically transformed if the constant is a power of 2.
I have modified constants like segments to values close to the power of 2.

Sorry for the inconvenience ^^

**Comment by badrishc** [comment]
No problem, look forward to your findings. You can fork the code, complete the work and then send us a PR to review.

**Pull request closed without merging**
